import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'es': {
      'welcome': 'Página Principal',
      'spaces': 'Inmuebles',
      'owners': 'Propietarios',
      'owners_count': 'Propietarios',
      'leads_count': 'Solicitudes',
      'inventory': 'Inventario de Locales',
      'carousel': 'Carrusel de Galería',
      'search': 'Buscar locales...',
      'budget': 'Generar Presupuesto',
      'login': 'Login',
      'about': 'Quiénes somos',
      'faq': 'Preguntas frecuentes',
      'tech_insights': 'Información Técnica',
      'res_inventory': 'Viviendas',
      'comm_inventory': 'Comercial',
      'avg_res_area': 'Área media Vivienda',
      'avg_comm_area': 'Área media Comercial',
      'construction_average': 'Año medio construcción',
      'amenities_title': 'Comodidades',
      'total_properties': 'Total Inmuebles',
      'property_count': '{0} Inmuebles',
      'tab_marketing': 'Marketing / Referidos',
      'tab_requests': 'Solicitudes',
      'country_pricing': 'Precios por País',
      'freelance_executives': 'Ejecutivos de Cuentas (Freelance)',
      'active_strategy': 'Estrategia de Referidos Activa',
      'strategy_1_desc': 'Estrategia 1: Descuento de \$1 USD mensual por referido.',
      'strategy_2_desc': 'Estrategia 2: Bonus de capacidad por referido + Comisiones a ejecutivos.',
      'strategy_3_desc': 'Estrategia 3 (Híbrida): Descuento de \$1.00 USD + Bonus de capacidad.',
      'salespersons': 'Ejecutivos de Cuentas',
      'salesperson': 'Ejecutivo de Cuentas',
      'new_salesperson': 'Nuevo Ejecutivo',
      'edit_salesperson': 'Editar Ejecutivo',
      'no_salespersons': 'No hay ejecutivos registrados',
      'alias': 'Alias / Seudónimo',
      'commission_pct': '% Comisión',
      'commissions': 'Comisiones',
      'pending': 'Pendiente',
      'paid': 'Pagado',
      'earning': 'Ganancia',
      'referred_companies': 'Agencias referidas',
      'successful_referrals': 'Invitaciones Exitosas',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'invalid_login': 'Credenciales inválidas',
      'admin_panel': 'Panel de Administración',
      'dashboard': 'Dashboard',
      'logout': 'Cerrar Sesión',
      'edit': 'Editar',
      'save': 'Guardar',
      'add_property': 'Agregar Local',
      'add_owner': 'Agregar Propietario',
      'me_interesa': 'Me Interesa',
      'estoy_interesado': 'Estoy Interesado',
      'quote_property': 'Cotizar Propiedad',
      'send': 'Enviar',
      'contact_us': 'Contáctanos',
      'home': 'Inicio',
      'my_panel': 'Mi Panel',
      'language': 'Idioma',
      'dark_mode': 'Modo Oscuro',
      'light_mode': 'Modo Claro',
      'advanced_filters': 'Filtros Avanzados',
      'no_results': 'No hay locales disponibles',
      'ref': 'Ref.',
      'property': 'Propiedad',
      'sale': 'Venta',
      'price_on_request': 'Precio a consultar',
      'residential': 'Viviendas',
      'commercial': 'Comercial',
      'investment': 'Inversión',
      'comm_local': 'Local comercial',
      'budget_intro': 'Cuéntanos un poco más sobre tu interés',
      'prop_interest': 'Inmueble de interés',
      'filter_address_label': 'Zona / Sector / Punto de referencia / Dirección / Nivel',
      'filter_address_hint': 'ejemplos: sector la charneca; california norte; la costanera; etc...',
      'full_name': 'Nombre completo',
      'invalid_email': 'Email inválido',
      'phone': 'Teléfono',
      'additional_notes': 'Notas adicionales',
      'my_profile': 'Mi Perfil',
      'share_profile': 'Compartir Perfil',
      'copy_link_success': 'Enlace copiado al portapapeles',
      'helper_notes': '¿Alguna condición o pregunta especial?',
      'buy': 'Comprar',
      'rent': 'Alquiler',
      'filters': 'Filtros',
      'reset': 'Limpiar todo',
      'apply': 'Aplicar Filtros',
      'newest': 'Nuevos',
      'price_asc': 'Precio Min',
      'price_desc': 'Precio Max',
      'most_popular': 'Más populares',
      'prop_type': 'Tipo de propiedad',
      'real_estate_companies': 'Inmobiliarias',
      'popularity': 'Popularidad',
      'popularity_switch_label': 'Solo mostrar inmuebles populares (> 5 likes)',
      'residential_cat': 'Viviendas',
      'commercial_cat': 'Comercial',
      'Posada': 'Posada',
      'store': 'Tienda',
      'hotel': 'Hotel',
      'agriculture': 'Agricultura y bosques',
      'penthouse': 'Ático',
      'duplex': 'Dúplex',
      'loft': 'Loft',
      'studio': 'Estudio',
      'carousel_manager': 'Carrusel',
      'change_password': 'Cambiar Contraseña',
      'gallery': 'Galería de Fotos',
      'add_image': 'Añadir Foto',
      'delete_image': 'Eliminar Foto',
      'set_main': 'Poner como Principal',
      'main_photo': 'Foto Principal',
      'uploading': 'Subiendo...',
      'about_title': 'Quiénes Somos',
      'about_p1': 'En NOMBRE AGENCIA, estamos redefiniendo el mercado inmobiliario mediante la integración de tecnología de vanguardia y un enfoque humano centrado en resultados. Nuestra misión es transformar la experiencia de encontrar el espacio ideal, eliminando fricciones y ofreciendo transparencia total en cada paso del proceso.',
      'about_p2': 'Como líderes en innovación digital, utilizamos plataformas avanzadas que permiten a nuestros clientes explorar inventarios en tiempo real, generar presupuestos inteligentes y gestionar citas de manera automatizada. Creemos que la eficiencia tecnológica es la clave para maximizar el valor de su tiempo y su inversión.',
      'about_p3': 'Nuestra especialización abarca desde residencias exclusivas hasta espacios comerciales estratégicos, siempre respaldados por una infraestructura digital robusta que garantiza seguridad y agilidad. En NOMBRE AGENCIA, no solo listamos propiedades, creamos ecosistemas de oportunidades para nuestros clientes.',
      'about_p4': 'La colaboración es parte de nuestro ADN. Gracias a nuestro sistema de alianzas estratégicas y referidos tecnológicos, conectamos a propietarios y buscadores de forma inteligente, ampliando el alcance de cada operación y garantizando que las mejores opciones siempre estén sobre la mesa.',
      'about_p5': 'El futuro de los bienes raíces es hoy, y en NOMBRE AGENCIA estamos listos para acompañarlo. Lo invitamos a experimentar una gestión inmobiliaria ágil, moderna y totalmente adaptada a las necesidades del mundo actual. Su próxima gran oportunidad comienza con un clic.',
      'faq_title': 'Preguntas Frecuentes',
      'faq1_q': '¿Cómo puedo solicitar un presupuesto para un inmueble?',
      'faq1_a': 'Es muy sencillo. Solo debe seleccionar el inmueble de su interés y hacer clic en el botón "Me Interesa" o "Cotizar". El sistema generará una solicitud formal y nuestro equipo le contactará a la brevedad con todos los detalles financieros.',
      'faq2_q': '¿Es posible agendar una visita física de forma online?',
      'faq2_a': 'Sí, contamos con una agenda digital integrada. Al consultar un inmueble, podrá ver la disponibilidad y solicitar una cita en el horario que mejor le convenga. Recibirá una confirmación automática una vez que el agente asigne la visita.',
      'faq3_q': '¿Qué seguridad ofrecen mis datos personales en la plataforma?',
      'faq3_a': 'En NOMBRE AGENCIA la privacidad es prioridad. Utilizamos infraestructura encriptada de última generación para asegurar que su información personal y sus solicitudes de presupuesto estén protegidas bajo los más altos estándares de seguridad digital.',
      'faq4_q': '¿Cómo funciona el sistema de referidos para otras inmobiliarias?',
      'faq4_a': 'Fomentamos el crecimiento colaborativo. Si usted es parte de otra agencia, puede referir clientes o nuevas inmobiliarias a nuestra red y obtener beneficios automáticos en la plataforma, fortaleciendo el ecosistema inmobiliario global.',
      'faq5_q': '¿Los precios mostrados incluyen impuestos o gastos legales?',
      'faq5_a': 'Los precios base reflejan el valor del inmueble. Los detalles específicos sobre impuestos, comisiones de ley o gastos de registro se detallarán claramente en el presupuesto formal enviado a su correo electrónico.',
      'title_field': 'Título',
      'description_field': 'Descripción',
      'price_field': 'Precio',
      'type_field': 'Tipo',
      'address_field': 'Dirección',
      'operation_field': 'Operación',
      'status_field': 'Estado',
      'owner_field': 'Propietario',
      'public_field': 'Público',
      'area_field': 'M2',
      'bathrooms_field': 'Baños',
      'parking_field': 'Estacionamiento',
      'air_con_field': 'Aire Acondicionado',
      'storage_field': 'Maletero/Depósito',
      'save_first': 'Por favor, guarda el inmueble primero antes de añadir fotos.',
      'delete_confirm': '¿Estás seguro de que deseas eliminar esta foto?',
      'prop_type_local': 'Local',
      'prop_type_office': 'Oficina',
      'prop_type_warehouse': 'Almacén',
      'prop_type_other': 'Otro',
      'op_sale': 'Venta',
      'op_rent': 'Alquiler',
      'st_available': 'Disponible',
      'st_reserved': 'Reservado',
      'st_sold': 'Vendido',
      'owner_full_name': 'Nombre Completo',
      'owner_phone': 'Teléfono',
      'delete_owner_confirm': '¿Estás seguro de que deseas eliminar a este propietario?',
      'delete_confirm_short': '¿Estás seguro?',
      'owner_delete_error': 'No se puede eliminar: tiene propiedades asociadas. Error: ',
      'change_password_title': 'Cambiar Contraseña',
      'new_password': 'Nueva contraseña',
      'confirm_password': 'Confirmar nueva contraseña',
      'password_updated': 'Contraseña actualizada con éxito',
      'carousel_title': 'Carrusel Principal',
      'carousel_change': 'Cambiar',
      'carousel_updated': 'Imagen actualizada con éxito',
      'carousel_strategy': 'Estrategia del Carrusel',
      'carousel_strategy_manual': 'Manual (Imágenes Subidas)',
      'carousel_strategy_popular': 'Automático (Inmuebles Populares)',
      'carousel_slot_title': 'Posición',
      'carousel_select_image': 'Seleccionar imagen',
      'carousel_image_selected': 'Imagen seleccionada ✓',
      'carousel_action_label': 'Acción al hacer click (opcional)',
      'carousel_action_hint': 'Ref. del inmueble (ej: 032) o link (ej: https://...)',
      'carousel_action_save': 'Guardar',
      'carousel_action_saved': 'Posición guardada con éxito',
      'select_property': 'Por favor seleccione un inmueble',
      'budget_sent': 'Solicitud enviada con éxito. Pronto le contactaremos.',
      'contact_intro': 'Déjanos un mensaje y te contactaremos a la brevedad.',
      'contact_success': 'Mensaje enviado con éxito. Pronto le contactaremos.',
      'budget_error': 'Error al enviar: ',
      'error_generic': 'Error: ',
      'owner_required': 'Por favor, seleccione un propietario.',
      'save_error': 'Error al guardar: ',
      'leads': 'Solicitudes',
      'search_leads': 'Buscar solicitudes...',
      'leads_empty': 'No hay solicitudes aún',
      'leads_no_name': 'Sin nombre',
      'leads_date': 'Fecha',
      'leads_mark_responded': 'Marcar respondida',
      'leads_mark_rejected': 'Marcar rechazada',
      // Mapa / Ubicación
      'assign_location': 'Asignar Ubicación',
      'map_tap_hint': 'Toca el mapa para marcar la ubicación exacta del inmueble.',
      'confirm_location': 'Confirmar Ubicación',
      'geocoding_failed': 'No se pudo encontrar la dirección en el mapa.',
      'no_location': 'Ubicación no seleccionada',
      'search_location': 'Buscar dirección...',
      'delivery_status_field': 'Estado de entrega',
      'has_electricity_field': 'Electricidad',
      'has_water_connections_field': 'Puntos de agua',
      'has_restroom_access_field': 'Acceso a baños',
      'has_ac_connection_field': 'Conexión para A/A',
      'floor_level_field': 'Nivel del inmueble',
      'has_storage_office_area_field': 'Área interna para almacén/oficina',
      'obra_gris': 'Obra gris',
      'semi_acabado': 'Semi acabado',
      'listo_para_ocupar': 'Listo para ocupar',
      'incluido_en_direccion': 'Especificado en dirección',
      'planta_baja': 'Planta baja',
      'mezzanina': 'Mezzanina',
      'primer_piso': 'Primer piso',
      'segundo_piso': 'Segundo piso',
      'tercer_piso': 'Tercer piso',
      'cuarto_piso': 'Cuarto piso',
      'leads_status_pending': 'Pendiente',
      'leads_status_responded': 'Respondida',
      'leads_status_rejected': 'Rechazada',
      'content_management': 'Gestión de Contenido',
      'summary_title': 'Resumen General',
      'total_inventory': 'Total Inmuebles',
      'top_owners': 'Top Propietarios',
      'dist_by_op': 'Operación (V/A)',
      'avg_bedrooms': 'Promedio Habitaciones',
      'avg_bathrooms': 'Promedio Baños',
      'avg_parking': 'Promedio Estacionamientos',
      'unknown': 'Desconocido',
      'availability': 'Disponibilidad',
      'operation_mode': 'Modalidad de Operación',
      'property_types': 'Tipos de Inmueble',
      'about_us_tab': 'Quiénes Somos',
      'faq_tab': 'FAQ',
      'loading_content': 'Cargando contenido...',
      'intro_paragraphs': 'Párrafos',
      'paragraph_label': 'Párrafo {0}',
      'save_changes': 'Guardar Cambios',
      'location_has_props': 'No se puede eliminar "{0}". Tiene {1} inmuebles vinculados.',
      'checking_protection': 'Verificando protección...',
      'text_es': 'Texto (Español)',
      'text_en': 'Texto (Inglés)',
      'add_faq': 'Añadir FAQ',
      'save_all': 'Guardar Todo',
      'delete_confirm_title': '¿Eliminar pregunta?',
      'delete_confirm_body': 'Esta acción no se puede deshacer.',
      'cancel': 'Cancelar',
      'new_question': '(Nueva Pregunta)',
      'sort_order': 'Orden',
      'success_about_updated': 'Contenido de "Quiénes Somos" actualizado',
      'success_company_updated': 'Ajustes de la agencia actualizados con éxito',
      'success_faqs_updated': 'Preguntas Frecuentes actualizadas',
      'Disponible': 'Disponible',
      'Reservado': 'Reservado',
      'Vendido': 'Vendido',
      'Alquilado': 'Alquilado',
      'filter_all': 'Todos',
      'Vendido/Alquilado': 'Vendido/Alquilado',
      'Venta': 'Venta',
      'Alquiler': 'Alquiler',
      'Local comercial': 'Local comercial',
      'Oficina': 'Oficina',
      'Almacén': 'Almacén',
      'Galpon': 'Galpón',
      'Casa': 'Casa',
      'Casa vacacional': 'Casa vacacional',
      'Apartamento': 'Apartamento',
      'Apartamento vacacional': 'Apartamento vacacional',
      'Terreno': 'Terreno',
      'Ático': 'Ático',
      'Dúplex': 'Dúplex',
      'Loft': 'Loft',
      'Townhouse': 'Townhouse',
      'Estudio': 'Estudio',
      'Inversión': 'Inversión',
      'Tienda': 'Tienda',
      'Hotel': 'Hotel',
      'Restauración': 'Restauración',
      'Patio Industrial': 'Patio Industrial',
      'Local': 'Local comercial',
      'Agricultura y bosques': 'Agricultura y bosques',
       'Centro Comercial': 'Centro Comercial',
      'Otro': 'Otro',
      'bedrooms_field': 'Habitaciones',
      'floors_field': 'Niveles/Pisos',
      'garden_field': 'Jardín',
      'pool_field': 'Piscina',
      'furnished_field': 'Amoblado',
      'interior_location_field': 'Ubicación Interna (Local/Nivel)',
      'spaces_count': '{0} espacios',
      'question': 'Pregunta',
      'answer': 'Respuesta',
      'any_value': 'Cualquiera',
      'min_label': 'Mín',
      'max_label': 'Máx',
      'minimum_suffix': '(mínimo)',
      'security_availability': 'Disponibilidad seguridad',
      'pool_availability': 'Disponibilidad piscina',
      'additional_features': 'Comodidades',
      'terrace_field': 'Terraza',
      'balcony_field': 'Balcón',
      'patio_field': 'Patio',
      'garage_field': 'Garaje',
      'power_generator_field': 'Planta Eléctrica',
      'water_tank_field': 'Tanque de Agua',
      'grill_field': 'Parrillera',
      'elevator_field': 'Ascensor',
      'security_field': 'Seguridad',
      'pets_allowed_field': 'Permite Mascotas',
      'children_allowed_field': 'Permite Niños',
      'waterfront_field': 'Frente al mar',
      'seaview_field': 'Vista al mar',
      'year_built_field': 'Año de Construcción',
      'plot_area_field': 'Superficie Parcela (m²)',
      'basement_field': 'Sótano',
      'fitted_kitchen_field': 'Cocina',
      'tennis_court_field': 'Pista de Tenis',
      'interior_location_hint': 'Ej: Local 5, Nivel 1 / Planta 2, Apt 4B',
      'Piscina': 'Piscina',
      'Terraza': 'Terraza',
      'Balcón': 'Balcón',
      'Patio': 'Patio',
      'Garaje': 'Garaje',
      'Ascensor': 'Ascensor',
      'Seguridad': 'Seguridad',
      'Permite Mascotas': 'Permite Mascotas',
      'Permite Niños': 'Permite Niños',
      'Frente al mar': 'Frente al mar',
      'Amoblado': 'Amoblado',
      'Sótano': 'Sótano',
      'Vista al mar': 'Vista al mar',
      'Cocina Empotrada': 'Cocina Empotrada',
      'Parrillera': 'Parrillera',
      // Geolocation
      'country_field': 'País',
      'state_field': 'Estado/Provincia',
      'location_section': 'Localización Geográfica',
      'filter_country': 'País',
      'filter_state': 'Estado/Provincia',
      'filter_city': 'Ciudad',
      'locations_manager': 'Gestor de Ubicaciones',
      'dist_by_city': 'Distribución por Ciudad',
      'props': 'props',
      'locations_menu': 'Localizaciones',
      'add_new_country': 'Agregar Nuevo País',
      'select_country': 'Selecciona un país',
      'select_state': 'Selecciona un estado',
      'confirm_delete': 'Confirmar Eliminación',
      'sure_delete_country': '¿Estás seguro de eliminar el país \$val y todos sus estados y ciudades?',
      'sure_delete_state': '¿Estás seguro de eliminar el estado \$val y todas sus ciudades?',
      'sure_delete_city': '¿Eliminar la ciudad \$val?',
      'add_state_to': 'Agregar Estado a',
      'add_city_to': 'Agregar Ciudad a',
      'delete': 'Eliminar',
      'add': 'Agregar',
      'name_hint': 'Nombre...',
      'geo_select_country': 'Selecciona un país',
      'geo_select_state': 'Selecciona un estado',
      'geo_select_city': 'Selecciona una ciudad',
      'geo_distribution': 'Distribución Geográfica',
      'top_cities': 'Inmuebles por Ciudad',
      // Super Admin Panel
      'super_admin_panel': 'Panel del Súper Administrador',
      'edit_company': 'Editar Agencia',
      'new_company': 'Nueva Agencia',
      'company_name': 'Nombre Comercial',
      'company_abbr': 'Abreviatura (3-5 letras)',
      'company_domain': 'Dominio Web',
      'primary_color': 'Color Principal (Hex)',
      'secondary_color': 'Color Secundario (Hex)',
      'contact_email': 'Email de Contacto',
      'contact_phone': 'Teléfono de Contacto',
      'is_demo': '¿Es Demo?',
      'is_active': 'Activa',
      'no_companies': 'No hay agencias registradas',
      'deactivate': 'Desactivar',
      'activate': 'Activar',
      'refresh': 'Actualizar',
      // Buscador global
      'global_search_subtitle': 'Buscador Global de Inmuebles',
      'global_search_hint': 'Buscar en todas las agencias...',
      'all_companies': 'Todas',
      'results': 'resultados',
      // Gestión de equipo (Agentes y Administrador)
      'users_management': 'Equipo',
      'agents': 'Agentes',
      'new_user': 'Nuevo Agente',
      'edit_user': 'Editar Agente',
      'role': 'Rol',
      'role_super_admin': 'Súper Admin',
      'role_admin': 'Administrador',
      'role_company_admin': 'Administrador de Agencia',
      'role_agent': 'Agente',
      'role_client': 'Cliente',
      'photo_of': 'Foto {0} de {1}',
      'assign_company': 'Asignar Agencia',
      'no_company': '(Sin agencia)',
      'no_users': 'No hay agentes registrados',
      'super_panel': 'Súper Panel',
      'login_intro': 'Introduzca sus credenciales',
      // Demo
      'demo_banner': '🎭 Agencia de demostración — los cambios pueden resetearse periódicamente',
      'demo_budget_disabled': 'Funcionalidad deshabilitada en modo demostración',
      // Super Admin tabs
      'tab_companies': 'Agencias',
      'tab_users': 'Equipo',
      'company_logos': 'Logos de la Agencia',
      'full_logo': 'Logo para PC',
      'abbr_logo': 'Logo Móviles',
      'social_networks': 'Redes Sociales',
      'referral_affiliate_settings': 'REFERIDOS Y AFILIADOS',
      'show_referral_option_desc': 'Permite invitar a otras agencias inmobiliarias desde el menú',
      'show_organic_affiliate_desc': 'Muestra el banner de registro para Agencia Inmobiliaria en la página de inicio',
      'who_acquired_company': '¿Quién captó a tu agencia?',
      'referred_companies_count': 'Agencias referidas por ti: {0}',
      'channel_organic': 'Lo encontré por mi cuenta',
      'channel_salesperson': 'Un vendedor me recomendó',
      'channel_broker': 'Otro corredor me recomendó',
      'salesperson_alias': 'Seudónimo del Ejecutivo',
      'inviting_company_email': 'Correo de tu Inmobiliaria que Invita',
      'regional_settings': 'CONFIGURACIÓN REGIONAL',
      'meters_unit': 'Metros (m²)',
      'feet_unit': 'Pies (ft²)',
      'commission_settings': 'CONFIGURACIÓN DE COMISIONES',
      'property_sales': 'VENTAS DE INMUEBLES',
      'agency_label': 'Agencia',
      'agents_label': 'Agentes',
      'split_auto_calc': '* El reparto se calcula automáticamente',
      'rentals_one_time': 'ALQUILER DE INMUEBLES',
      'residential_months': 'Residencial (Meses)',
      'commercial_months': 'Comercial (Meses)',
      'rental_management_title': 'GESTIÓN DE COBRANZA (ALQUILERES)',
      'monthly_commission': 'Comisión Mensual',
      'rental_fee_pct': '% del canon de arrendamiento mensual',
      'taxes_billing': 'IMPUESTOS (PARA FACTURACIÓN)',
      'tax_label_field': 'Etiqueta de Impuesto',
      'tax_percentage_field': 'Porcentaje',
      'legal_entity_tax_note': '* Se aplica a facturas de Propietarios "Persona Jurídica"',
      'plan_subscription': 'PLAN Y SUSCRIPCIÓN',
      'plan_status': 'Estado del Plan:',
      'days_remaining_label': 'Días restantes: {0}',
      'whatsapp_full_label': 'WhatsApp (Número completo)',
      // Billing Tab
      'tab_billing': 'Facturación',
      'check_subs': 'Verificar Suscripciones (Cron)',
      'batch_reminder': 'Recordatorio Lote (5 días)',
      'register_payment': '✅ Registrar Pago',
      'reactivate_btn': '🔓 Reactivar',
      'suspend_btn': '🚫 Suspender',
      'payment_confirm_title': 'Confirmar Pago',
      'amount_placeholder': 'Monto (USD)',
      'ref_placeholder': 'Referencia / Banco',
      'notes_placeholder': 'Notas (Opcional)',
      'origin_bank': 'Banco Origen',
      'submit_payment': 'Enviar Pago',
      'confirm_activate': 'Confirmar y Activar',
      'suspend_company_q': '¿Suspender agencia?',
      'suspend_company_warn': 'Esto bloqueará el acceso a {0} inmediatamente.',
      // Agenda/Calendar
      'agenda': 'Agenda',
      'agenda_new_appointment': 'Nueva Cita',
      'agenda_edit_appointment': 'Editar Cita',
      'agenda_client_name': 'Nombre del cliente',
      'agenda_phone': 'Teléfono',
      'agenda_date': 'Fecha de la cita',
      'agenda_time': 'Hora',
      'agenda_property': 'Propiedad a visitar',
      'agenda_search_property': 'Buscar propiedad...',
      'agenda_status': 'Estado de la cita',
      'agenda_status_pending': 'Pendiente',
      'agenda_status_confirmed': 'Confirmada',
      'agenda_status_cancelled': 'Cancelada',
      'agenda_status_done': 'Realizada',
      'agenda_no_appointments': 'No hay citas este día',
      'agenda_today_badge': 'citas hoy',
      'agenda_delete_confirm': '¿Eliminar esta cita?',
      'agenda_saved': 'Cita guardada',
      'agenda_deleted': 'Cita eliminada',
      'agenda_select_property': 'Selecciona una propiedad',
      'agenda_search_hint': 'Busca por Ref.',
      'agenda_today': 'Hoy',
      'agenda_month_view': 'Mes',
      'agenda_week_view': 'Semana',
      'agenda_day_view': 'Día',
      'agenda_assigned_agent': 'Agente asignado',
      'agenda_all_agents': 'Todos los agentes',
      'agenda_select_agent': 'Seleccionar agente',
      'agenda_prop_ref': 'Ref. Propiedad / Prop. Ref.',
      'selected_label': 'Seleccionado',
      'view_on_map': 'Ver en mapa',
      'my_location': 'Mi ubicación',
      'assign_on_map': 'Ubicar en el mapa',
      'geocode_address': 'Geocodificar dirección',
      'location_not_found': 'No se pudo encontrar la ubicación: {0}',
      'geocoding': 'Buscando coordenadas...',
      'coordinates_field': 'Coordenadas (Lat, Lng)',
      'loc_not_specified': 'Ubicación no especificada',
      'property_location': 'Propiedad',
      'user_location': 'Tú',
      'weekly_visitors': '{0} visitas',
      'this_week': 'esta semana',
      'invite_re_agency': 'Invitar a otra Inmobiliaria',
      'invite_godmother_agency': 'Agencia que Invita (Tu Inmobiliaria)',
      'invite_godmother_email': 'Tu Correo de Contacto',
      'invite_recipient_email': 'Correo de la Agencia Receptora',
      'invite_email_hint': 'Ejemplo: contacto@inmobiliariaamiga.com',
      'invite_send_btn': 'ENVIAR INVITACIÓN',
      'invite_success_title': '¡Invitación Enviada!',
      'invite_success_msg': 'Cuando la agencia se registre exitosamente, recibirás tus premios en el sistema.',
      'invite_send_another': 'Enviar otra invitación',
      'invite_desc': 'Invita a otra inmobiliaria a unirse a la plataforma y gana bonificaciones automáticas cada vez que una agencia complete su registro gracias a ti.',
      'invite_title_card': 'Crece con Alveo',
      'invite_reward_properties': '+2 Inmuebles',
      'invite_reward_properties_desc': 'de límite',
      'invite_reward_photos': '+2 Fotos',
      'invite_reward_photos_desc': 'por inmueble',
      'invite_reward_discount': '-\$1 Mes',
      'invite_reward_discount_desc': 'Dcto mensual',
      'invite_disclaimer': '*Límite de rebaja acumulado: 25% del valor de tu plan. Las capacidades espaciales no tienen tope.',
      'required': 'Requerido',
      'trial_info_with_price': 'Prueba gratis por 7 días. Luego {0}/mes.',
      // Register screen
      'register_title': 'Únete a Alveo',
      'register_hero': '🚀 Crea tu propia plataforma inmobiliaria hoy.',
      'register_trial_info': 'Prueba gratis por 7 días. Luego \${0}/mes.',
      'register_trial_info_unknown': 'Prueba gratis por 7 días.',
      'register_logo_pc': 'Logo para PC',
      'register_logo_mobile': 'Logo Móviles',
      'register_company_name': 'Nombre de Inmobiliaria',
      'register_domain_label': 'Tu Dirección en Alveo (Link)',
      'register_domain_helper': 'Elige un nombre corto para tu portal (ej: miagencia). Solo letras minúsculas y números. Este será tu link permanente.',
      'register_subdomain_hint': 'ej: miagencia',
      'register_domain_unavailable': 'Dominio no disponible',
      'register_domain_available': '✅ Dominio disponible',
      'register_url_preview': 'Tu URL será',
      'register_your_name': 'Tu Nombre',
      'register_email': 'Correo electrónico',
      'register_email_hint': 'correo electrónico que exista',
      'register_email_invalid': 'Correo inválido',
      'register_password': 'Contraseña (Admin)',
      'register_password_min': 'Mínimo 6 caracteres',
      'register_phone': 'Teléfono',
      'register_social_networks': 'Redes Sociales',
      'register_whatsapp_required': 'WhatsApp requerido',
      'register_language': 'Idioma de tu Plataforma',
      'register_plan': 'Plan',
      'register_plan_monthly': 'Mensual: \${0}',
      'register_plan_annual': 'Anual: \${0}',
      'register_trial_start': 'Inicio de Prueba (7 días)',
      'register_trial_end': 'Vencimiento Prueba',
      'register_regional': 'Configuración Regional',
      'register_detecting': 'Detectando tu ubicación...',
      'register_detected': 'País detectado por tu IP: {0}',
      'register_ip_locked': 'El país se detectó automáticamente por tu IP y no puede cambiarse para garantizar el precio correcto.',
      'register_ip_lock_icon': 'País bloqueado por detección IP',
      'register_branding': 'Colores de la Agencia',
      'register_primary_color': 'Color Principal',
      'register_secondary_color': 'Color Secundario',
      'register_hex_link': 'Obtén tus códigos hexadecimales aquí: htmlcolorcodes.com',
      'register_how': '¿Cómo conociste Alveo?',
      'register_channel_organic': 'Orgánico (iniciativa propia)',
      'register_channel_salesperson': 'Por ejecutivo de venta y soporte',
      'register_channel_broker': 'Otra agencia inmobiliaria',
      'register_alias_label': 'Seudónimo del vendedor',
      'register_alias_hint': 'ej: lenin123',
      'register_broker_email': 'Correo de la agencia que invita',
      'register_referred_by': 'Recomendado por:\n{0}',
      'register_recommended_by': 'Recomendado por:\n{0}',
      'register_add_referral': 'Añadir referido',
      'register_change': 'Cambiar',
      'register_broker_question': '¿Otra agencia te invitó?',
      'register_submit': 'Registrarse ahora',
      'register_domain_check_first': 'Por favor verifica la disponibilidad del subdominio antes de continuar.',
      'register_success_title': '¡Felicidades! Tu plataforma Alveo está lista',
      'register_success_access': 'Ya puedes acceder a tu portal en:',
      'register_success_email': '📧 Revisa tu correo para ver tus credenciales de acceso.',
      'register_go_portal': 'IR A MI PORTAL AHORA',
      'register_welcome_email_sent': 'También hemos enviado un correo de bienvenida a {0}.',
      'view_billing_history': 'VER HISTORIAL DE PAGOS',
      'report_payment_title': 'Reportar Pago',
      'report_payment_desc': 'Introduce los detalles de tu transferencia bancaria para renovar tu suscripción.',
      'origin_bank_label': 'Banco Origen',
      'origin_bank_hint': 'Ej: Banesco, Mercantil...',
      'reference_number_label': 'Número de Referencia',
      'reference_required': 'Referencia requerida',
      'current_plan_label': 'Plan actual: {0}',
      'payment_reported_success': 'Pago reportado con éxito. El administrador lo revisará pronto.',
      'trial_ending_soon': 'Tu prueba gratuita termina en {0} {1}.',
      'subscription_expired_urgent': 'Suscripción vencida. ¡Paga pronto para evitar la suspensión!',
      'subscription_ending_soon': 'Tu suscripción vence en {0} {1}.',
      'confirm_rejection_title': 'Confirmar Rechazo',
      'confirm_rejection_msg': '¿Estás seguro de que deseas rechazar esta solicitud? Esta acción no se puede deshacer.',
      'super_admin_billing_tab_title': 'Facturación',
      'company_logos_title': 'LOGOS DE LA AGENCIA',
      'general_summary_title': 'RESUMEN GENERAL',
      'contact_info_title': 'INFORMACIÓN DE CONTACTO',
      'regional_settings_title': 'AJUSTES REGIONALES',
      'plan_limits_title': 'PLAN Y CAPACIDADES',
      'mrr_real_label': 'MRR (Real 30d)',
      'mrr_potential_label': 'MRR (Potencial)',
      'subscribers_label': 'Suscritos',
      'trial_users_label': 'En Prueba',
      'suspended_users_label': 'Suspendidos',
      'pending_label': 'Pendientes',
      'pending_approvals_title': 'Pagos Pendientes de Aprobación',
      'no_pending_payments': 'No hay pagos pendientes.',
      'receipt_label': 'Comprobante:',
      'view_fullscreen': 'Ver Pantalla Completa',
      'reject_btn': 'Rechazar',
      'approve_activate_btn': 'Aprobar y Activar',
      'close_btn': 'Cerrar',
      'billing_cycle_label': 'Ciclo de Facturación / Plan',
      'base_price_label': 'Precio Base \$ (Mensual)',
      'max_props_label': 'Límite Inmuebles Base',
      'max_photos_label': 'Límite Fotos Base',
      'show_referral_option': 'Mostrar Opción de Referidos',
      'show_organic_affiliate': 'Mostrar Banner de Afiliación Orgánica',
      'global_settings_title': 'Ajustes Globales (Por Defecto)',
      'active': 'ACTIVA',
      'inactive': 'INACTIVA',
      'm2': 'Metros (m²)',
      'ft2': 'Pies (ft²)',
      'area_unit_label': 'Unidad de Área',
      'currency_label': 'Moneda Default',
      'start_date_label': 'Fecha Inicio',
      'expiration_date_label': 'Vencimiento',
      'min_limit_label': 'Límite Mín (-25%)',
      'full_logo_label': 'Logo Principal',
      'abbr_logo_label': 'Logo Abreviado',
      'approve_request_title': 'Aprobar Solicitud',
      'approve_request_body': '¿Deseas crear la agencia "{0}" y activarla en Trial?',
      'approve_create_btn': 'Aprobar y Crear',
      'company_created_activated': 'Agencia creada y activada',
      'no_pending_requests': 'No hay solicitudes pendientes',
      'contact_label_field': 'Contacto:',
      'domain_label_field': 'Dominio:',
      'special_country_price': 'Precio especial por país',
      'standard_price': 'Precio estándar',
      'per_month': '/mes',
      'per_year_annual': '/año (anual)',
      'approve_activate_trial_btn': 'APROBAR Y ACTIVAR TRIAL',
      'strategy_updated': 'Estrategia actualizada a: {0}',
      'alias_name_required': 'Alias y Nombre son obligatorios',
      'country_header': 'PAÍS',
      'monthly_header': 'MENSUAL',
      'annual_header': 'ANUAL',
      'floor_price_header': 'PISO REF.',
      'delete_country_price_title': 'Eliminar precio especial',
      'delete_country_price_body': '¿Deseas eliminar el precio configurado para {0} y volver al base global?',
      'monthly_price_label_field': 'Precio mensual (USD, mín. \$5)',
      'floor_price_label_field': 'Piso referidos (mín. \$5)',
      'floor_price_helper': 'Precio mínimo tras descuentos por referidos',
      'annual_calculated': 'Anual calculado: \$',
      'one_month_free': '(1 mes gratis)',
      'min_5_error': 'Mínimo \$5.00',
      'floor_min_5_error': 'Piso mínimo \$5.00',
      'floor_greater_error': 'Piso no puede ser mayor que el mensual',
      'bank_account_info_field': 'Información Bancaria',
      'deactivate_salesperson_title': 'Desactivar Ejecutivo',
      'deactivate_salesperson_body': '¿Estás seguro de que deseas desactivar a "{0}"? Seguirá en el sistema pero no podrá ser asignado a nuevas operaciones.',
      'commissions_empty': 'No hay comisiones registradas',
      'mark_paid': 'Marcar Pagado',
      'active_btn': 'Activo',
      'inactive_btn': 'Inactivo',
      'date_header': 'Fecha',
      'company_header': 'Agencia',
      'amount_header': 'Monto',
      'status_header': 'Estado',
      'actions_header': 'Acciones',
      'user_deleted_success': 'Agente eliminado con éxito',
      'no_name': 'Sin nombre',
      // Contract
      'contract_section_header': '📄 Revisa y acepta el contrato antes de continuar',
      'contract_accept': 'He leído y acepto el Contrato de Prestación de Servicios con Alveo',
      'contract_accept_date': 'Fecha de aceptación',
      'contract_required': 'Debes aceptar el contrato para poder enviar tu solicitud',
      // Social Networks
      'whatsapp_label': 'WhatsApp *',
      'instagram_label': 'Instagram',
      'facebook_label': 'Facebook',
      'telegram_label': 'Telegram',
      // Regional
      'state_label': 'Estado / Provincia',
      'city_field': 'Ciudad',
      'currency_label_field': 'Moneda',
      'unit_label_field': 'Unidad de Área',
      'meters_label': 'Metros (m²)',
      'feet_label': 'Pies (ft²)',
      // Prices
      'special_price_for': '¡Precio especial para {0}!',
      'standard_price_for': 'Precio estándar para {0}',
      'monthly_short': 'Mensual',
      'annual_short': 'Anual',
      // Months
      'month_1': 'enero', 'month_2': 'febrero', 'month_3': 'marzo', 'month_4': 'abril',
      'month_5': 'mayo', 'month_6': 'junio', 'month_7': 'julio', 'month_8': 'agosto',
      'month_9': 'septiembre', 'month_10': 'octubre', 'month_11': 'noviembre', 'month_12': 'diciembre',
      'month_1_abbr': 'Ene', 'month_2_abbr': 'Feb', 'month_3_abbr': 'Mar', 'month_4_abbr': 'Abr',
      'month_5_abbr': 'May', 'month_6_abbr': 'Jun', 'month_7_abbr': 'Jul', 'month_8_abbr': 'Ago',
      'month_9_abbr': 'Sep', 'month_10_abbr': 'Oct', 'month_11_abbr': 'Nov', 'month_12_abbr': 'Dic',
      'clear_filter': 'Limpiar Filtro',
      'filter_by_date': 'Filtrar por Fecha',
      'commissions_trend': 'Tendencia de Comisiones',
      'popular_likes': 'Populares (Likes)',
      'popular_views': 'Populares (Vistas)',
      'no_chart_data': 'No hay datos suficientes para la gráfica.',
      'total_collected': 'Total Cobrado',
      'agency_retention': 'Retención Agencia',
      'pending_payouts': 'Pendiente de Pago',
      'commission_detail': 'Detalle',
      'operation_details': 'Detalles de la Operación',
      'location': 'Ubicación',
      'operation': 'Operación',
      'close_date': 'Fecha Cierre',
      'total_commission': 'Comisión Total',
      'agency_retention_pct': 'Retención Agencia ({0}%)',
      'agent_pool': 'Pool Agentes',
      'agent_distribution': 'Distribución a Agentes',
      'agent_unknown': 'Agente Desconocido',
      'commission_pct_of': '{0}% de la comisión',
      'company_must_collect_first': 'La agencia debe cobrar la comisión primero.',
      'confirm_payment': 'Confirmar Pago',
      'confirm_payment_body': '¿Confirmas el pago de {0} a {1}?',
      'confirm': 'Confirmar',
      'current_status': 'Estado Actual:',
      'mark_collected': 'Marcar Cobrada',
      'delete_commission': 'Eliminar Comisión',
      'delete_commission_body': '¿Estás seguro de eliminar esta comisión? El inmueble volverá a estar "Disponible".',
      'commission_deleted': 'Comisión eliminada con éxito.',
      'delete_error': 'Error al eliminar: {0}',
      'pdf_error': 'Error al generar PDF: {0}',
      'client_name_required': 'Ingrese el nombre del cliente para Otros Servicios.',
      'agent_split_error': 'La suma de porcentajes debe ser 100% (Actual: {0}%)',
      'commission_registered': 'Comisión registrada exitosamente.',
      'client_name': 'Nombre del Cliente',
      'op_rental_mgmt': 'Gestión de Alquileres',
      'op_other_services': 'Otros Servicios',
      'final_price': 'Precio Final (\$)',
      'commission_collected': 'Comisión Cobrada (\$)',
      'agency_amount': 'Monto Agencia',
      'notes_optional': 'Notas (Opcional)',
      'notes': 'Notas:',
      'concept_label': 'Por concepto de:',
      'agent_split': 'División de Agentes',
      'add_agent': 'Agregar Agente',
      'total_must_be_100': 'El total debe ser 100%. Actual: {0}%',
      'agent': 'Agente',
      'register_operation': 'Registrar Operación y Comisión',
      'all': 'Todos',
      'owner': 'Propietario',
      'person_type': 'Tipo de Persona',
      'default_commission_pct': 'Comisión Default %',
      'tax_settings': 'Ajustes de Impuestos',
      'tax_label': 'Etiqueta de Impuesto',
      'tax_percentage': 'Porcentaje de Impuesto',
      'confirm_save_commission': 'Confirmar Comisión',
      'confirm_save_commission_body': '¿Deseas guardar los cambios en esta comisión?',
      'pdf_internal': 'Operación',
      'pdf_invoice': 'Factura Propietario',
      'pdf_agent_receipts': 'Recibos Agentes',
      'no_agents_to_pay': 'No hay agentes asignados',
      'no_owner_found': 'Propietario no encontrado',
      'signature': 'Firma',
      'amount_received': 'Monto Recibido',
      'footer': 'Este documento es un comprobante digital generado por Alveo Real Estate Platform.',
      'invoice_title': 'FACTURA DE COMISIÓN',
      'tax_id': 'ID Fiscal',
      'received_from': 'Recibido de:',
      'agent_name': 'A favor de:',
      'agent_receipt': 'RECIBO DE PAGO',
      'Persona Natural': 'Persona Natural',
      'Persona Juridica': 'Persona Jurídica',
      'Ente Gubernamental': 'Ente Gubernamental',
      'total_filtered': 'Total Filtrado',
      'all_f': 'Todos',
      'pending_plural': 'Pendientes',
      'collected_plural': 'Cobradas',
      'paid_plural': 'Pagadas',
      'no_commissions': 'No hay comisiones registradas.',
      'unknown_property': 'Inmueble desconocido',
      'closed': 'Cerrado',
      'register_commission': 'Registrar Comisión',
      'collected_f': 'Cobrada',
      'paid_f': 'Pagada',
      'export_excel': 'Exportar a Excel',
      'excel_report_generated': 'Reporte de Excel generado con éxito',
      'excel_generation_error': 'Error al generar Excel: {0}',
      'limit_reached_msg': 'Límite de inmuebles alcanzado. ¡Refiere a otro corredor para ganar +2 cupos!',
      'my_public_profile': 'Mi Perfil Público',
      'username_slug': 'Enlace Personal (Alias)',
      'username_slug_help': 'Este será tu enlace web único para compartir tu catálogo con los clientes:',
      'username_hint': 'Solo letras minúsculas, números y guiones',
      'contact_whatsapp': 'WhatsApp de contacto',
      'bio_description': 'Biografía / Descripción',
      'link_preview': 'Vista previa de tu link:',
      'link_copied': 'Link copiado al portapapeles',
      'save_success': 'Guardado con éxito',
      'my_commissions': 'Mis Comisiones',
    },
    'en': {
      'welcome': 'Home Page',
      'spaces': 'Properties',
      'inventory': 'Properties Inventory',
      'carousel': 'Gallery Carousel',
      'search': 'Search spaces...',
      'budget': 'Request Quote',
      'about': 'About Us',
      'faq': 'FAQ',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'invalid_login': 'Invalid credentials',
      'admin_panel': 'Admin Panel',
      'dashboard': 'Dashboard',
      'referral_affiliate_settings': 'REFERRALS & AFFILIATES',
      'show_referral_option_desc': 'Allows inviting other real estate agencies from the menu',
      'show_organic_affiliate_desc': 'Shows the real estate agency registration banner on the home page',
      'who_acquired_company': 'Who acquired your agency?',
      'referred_companies_count': 'Agencies referred by you: {0}',
      'channel_organic': 'I found it myself',
      'channel_salesperson': 'A salesperson recommended me',
      'channel_broker': 'Another broker recommended me',
      'salesperson_alias': 'Salesperson Alias',
      'inviting_company_email': 'Inviting Agency Email',
      'regional_settings': 'REGIONAL SETTINGS',
      'language_label': 'Language',
      'meters_unit': 'Meters (m²)',
      'feet_unit': 'Feet (ft²)',
      'commission_settings': 'COMMISSION SETTINGS',
      'property_sales': 'PROPERTY SALES',
      'agency_label': 'Agency',
      'agents_label': 'Agents',
      'split_auto_calc': '* Split is calculated automatically',
      'rentals_one_time': 'Property Rentals',
      'residential_months': 'Residential (Months)',
      'commercial_months': 'Commercial (Months)',
      'rental_management_title': 'Collection Management (Rentals)',
      'monthly_commission': 'Monthly Commission',
      'rental_fee_pct': '% of monthly rental fee',
      'taxes_billing': 'TAXES (FOR BILLING)',
      'tax_label_field': 'Tax Label',
      'tax_percentage_field': 'Percentage',
      'legal_entity_tax_note': '* Applied to "Legal Entity" Owner invoices',
      'plan_subscription': 'PLAN & SUBSCRIPTION',
      'plan_status': 'Plan Status:',
      'days_remaining_label': 'Days remaining: {0}',
      'whatsapp_full_label': 'WhatsApp (Full number)',
      'logout': 'Logout',
      'edit': 'Edit',
      'save': 'Save',
      'send': 'Send',
      'country_pricing': 'Country Pricing',
      'freelance_executives': 'Account Executives (Freelance)',
      'salesperson': 'Account Executive',
      'new_salesperson': 'New Executive',
      'edit_salesperson': 'Edit Executive',
      'no_salespersons': 'No executives registered',
      'add_property': 'Add Space',
      'add_owner': 'Add Owner',
      'me_interesa': 'I\'m Interested',
      'estoy_interesado': 'I\'m Interested',
      'contact_us': 'Contact Us',
      'home': 'Home',
      'my_panel': 'My Panel',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'advanced_filters': 'Advanced Filters',
      'tech_insights': 'Technical Insights',
      'res_inventory': 'Residential',
      'comm_inventory': 'Commercial',
      'avg_res_area': 'Avg residential area',
      'avg_comm_area': 'Avg commercial area',
      'construction_average': 'Avg year built',
      'amenities_title': 'Features',
      'total_properties': 'Total Properties',
      'property_count': '{0} Properties',
      'year_range': 'Year range',
      'no_results': 'No spaces available',
      'ref': 'Ref.',
      'property': 'Property',
      'sale': 'Sale',
      'price_on_request': 'Price upon request',
      'residential': 'Residential',
      'commercial': 'Commercial',
      'investment': 'Investment',
      'comm_local': 'Commercial local',
      'budget_intro': 'Tell us more about your interest',
      'prop_interest': 'Property of interest',
      'required': 'Required',
      'filter_address_label': 'Area / Sector / Landmark / Address / Level',
      'filter_address_hint': 'examples: sector la charneca; california norte; la costanera; etc...',
      'full_name': 'Full Name',
      'invalid_email': 'Invalid email',
      'phone': 'Phone',
      'additional_notes': 'Additional notes',
      'my_profile': 'My Profile',
      'share_profile': 'Share Profile',
      'copy_link_success': 'Link copied to clipboard',
      'helper_notes': 'Any special conditions or questions?',
      'buy': 'Buy',
      'rent': 'Rent',
      'filters': 'Filters',
      'reset': 'Clear All',
      'apply': 'Apply Filters',
      'newest': 'Newest',
      'price_asc': 'Price Asc',
      'price_desc': 'Price Desc',
      'most_popular': 'Most Popular',
      'prop_type': 'Property Type',
      'real_estate_companies': 'Real Estate Agencies',
      'popularity': 'Popularity',
      'popularity_switch_label': 'Only show popular properties (> 5 likes)',
      'residential_cat': 'Residential',
      'commercial_cat': 'Commercial',
      'Posada': 'Inn',
      'store': 'Shop',
      'hotel': 'Hotel',
      'agriculture': 'Agriculture & Forests',
      'penthouse': 'Penthouse',
      'duplex': 'Duplex',
      'loft': 'Loft',
      'studio': 'Studio',
      'carousel_manager': 'Carousel',
      'change_password': 'Change Password',
      'gallery': 'Photo Gallery',
      'add_image': 'Add Photo',
      'delete_image': 'Delete Photo',
      'set_main': 'Set as Main',
      'main_photo': 'Main Photo',
      'uploading': 'Uploading...',
      'about_title': 'About Us',
      'about_p1': 'At NOMBRE AGENCIA, we are redefining the real estate market by integrating cutting-edge technology with a human-centric approach focused on results. Our mission is to transform the experience of finding the ideal space, removing friction and offering total transparency at every step of the process.',
      'about_p2': 'As leaders in digital innovation, we use advanced platforms that allow our clients to explore inventories in real time, generate smart quotes, and manage appointments automatically. We believe that technological efficiency is the key to maximizing the value of your time and investment.',
      'about_p3': 'Our specialization ranges from exclusive residences to strategic commercial spaces, always backed by a robust digital infrastructure that guarantees security and agility. At NOMBRE AGENCIA, we don\'t just list properties; we create ecosystems of opportunities for our clients.',
      'about_p4': 'Collaboration is part of our DNA. Thanks to our strategic alliance and technological referral system, we intelligently connect owners and seekers, expanding the reach of each operation and ensuring that the best options are always on the table.',
      'about_p5': 'The future of real estate is today, and at NOMBRE AGENCIA, we are ready to accompany you. We invite you to experience real estate management that is agile, modern, and fully adapted to the needs of today\'s world. Your next big opportunity starts with a click.',
      'faq_title': 'Frequently Asked Questions',
      'faq1_q': 'How can I request a quote for a property?',
      'faq1_a': 'It\'s very simple. Just select the property of interest and click the "I\'m Interested" or "Quote" button. The system will generate a formal request, and our team will contact you shortly with all the financial details.',
      'faq2_q': 'Is it possible to schedule a physical visit online?',
      'faq2_a': 'Yes, we have an integrated digital agenda. When inquiring about a property, you can see availability and request an appointment at a time that suits you best. You will receive an automatic confirmation once the agent assigns the visit.',
      'faq3_q': 'What security do my personal data offer on the platform?',
      'faq3_a': 'At NOMBRE AGENCIA, privacy is a priority. We use state-of-the-art encrypted infrastructure to ensure that your personal information and quote requests are protected under the highest digital security standards.',
      'faq4_q': 'How does the referral system work for other real estate agencies?',
      'faq4_a': 'We encourage collaborative growth. If you are part of another agency, you can refer clients or new real estate agencies to our network and obtain automatic benefits on the platform, strengthening the global real estate ecosystem.',
      'faq5_q': 'Do the prices shown include taxes or legal expenses?',
      'faq5_a': 'Base prices reflect the property\'s value. Specific details regarding taxes, legal commissions, or registration expenses will be clearly detailed in the formal quote sent to your email.',
      'title_field': 'Title',
      'description_field': 'Description',
      'price_field': 'Price',
      'type_field': 'Type',
      'address_field': 'Address',
      'operation_field': 'Operation',
      'status_field': 'Status',
      'owner_field': 'Owner',
      'public_field': 'Public',
      'area_field': 'Sq. Meters',
      'bathrooms_field': 'Bathrooms',
      'parking_field': 'Parking',
      'air_con_field': 'Air Conditioning',
      'storage_field': 'Storage',
      'save_first': 'Please save the property first before adding photos.',
      'delete_confirm': 'Are you sure you want to delete this photo?',
      'prop_type_local': 'Local',
      'prop_type_office': 'Office',
      'prop_type_warehouse': 'Warehouse',
      'prop_type_house': 'House',
      'prop_type_apartment': 'Apartment',
      'prop_type_land': 'Land',
      'prop_type_other': 'Other',
      'op_sale': 'Sale',
      'op_rent': 'Rent',
      'st_available': 'Available',
      'st_reserved': 'Reserved',
      'st_sold': 'Sold',
      'owner_full_name': 'Full Name',
      'owner_phone': 'Phone',
      'delete_owner_confirm': 'Are you sure you want to delete this owner?',
      'delete_confirm_short': 'Are you sure?',
      'owner_delete_error': 'Cannot delete: owner has associated properties. Error: ',
      'change_password_title': 'Change Password',
      'new_password': 'New password',
      'confirm_password': 'Confirm new password',
      'password_updated': 'Password updated successfully',
      'carousel_title': 'Main Carousel',
      'carousel_change': 'Change',
      'carousel_updated': 'Image updated successfully',
      'carousel_strategy': 'Carousel Strategy',
      'carousel_strategy_manual': 'Manual (Uploaded Images)',
      'carousel_strategy_popular': 'Automatic (Popular Properties)',
      'carousel_slot_title': 'Position',
      'carousel_select_image': 'Select image',
      'carousel_image_selected': 'Image selected ✓',
      'carousel_action_label': 'Click action (optional)',
      'carousel_action_hint': 'Property ref (e.g. 032) or link (e.g. https://...)',
      'carousel_action_save': 'Save',
      'carousel_action_saved': 'Slot saved successfully',
      'select_property': 'Please select a property',
      'budget_sent': 'Request sent successfully. We will contact you soon.',
      'contact_intro': 'Leave us a message and we will get back to you shortly.',
      'contact_success': 'Message sent successfully. We will contact you soon.',
      'budget_error': 'Error sending: ',
      'error_generic': 'Error: ',
      'owner_required': 'Please select an owner.',
      'save_error': 'Error saving: ',
      'leads': 'Requests',
      'search_leads': 'Search requests...',
      'leads_empty': 'No requests yet',
      'location_has_props': 'Cannot delete "{0}". It has {1} properties linked.',
      'checking_protection': 'Checking protection...',
      'leads_no_name': 'No name',
      'leads_date': 'Date',
      'leads_mark_responded': 'Mark responded',
      'leads_mark_rejected': 'Mark rejected',
      'leads_status_pending': 'Pending',
      'leads_status_responded': 'Responded',
      'leads_status_rejected': 'Rejected',
      'content_management': 'Content Management',
      'summary_title': 'General Summary',
      'total_inventory': 'Total Properties',
      'top_owners': 'Top Owners',
      'dist_by_op': 'Operation (Sale/Rent)',
      'avg_bedrooms': 'Avg Bedrooms',
      'avg_bathrooms': 'Avg Bathrooms',
      'avg_parking': 'Avg Parking',
      'unknown': 'Unknown',
      'availability': 'Availability',
      'operation_mode': 'Operation Mode',
      'property_types': 'Property Types',
      'about_us_tab': 'About Us',
      'faq_tab': 'FAQ',
      'loading_content': 'Loading content...',
      'intro_paragraphs': 'Paragraphs',
      'paragraph_label': 'Paragraph {0}',
      'save_changes': 'Save Changes',
      'text_es': 'Text (Spanish)',
      'text_en': 'Text (English)',
      'add_faq': 'Add FAQ',
      'save_all': 'Save All',
      'delete_confirm_title': 'Delete question?',
      'delete_confirm_body': 'This action cannot be undone.',
      'cancel': 'Cancel',
      'new_question': '(New Question)',
      'sort_order': 'Order',
      'success_about_updated': '"About Us" content updated',
      'success_company_updated': 'Agency settings updated successfully',
      'success_faqs_updated': 'FAQs updated',
      'Disponible': 'Available',
      'Reservado': 'Reserved',
      'Vendido': 'Sold',
      'Alquilado': 'Rented',
      'filter_all': 'All',
      'Vendido/Alquilado': 'Sold/Leased',
      'Venta': 'Sale',
      'Alquiler': 'Rent',
      'Local': 'Commercial Local',
      'Oficina': 'Office',
      'Almacén': 'Warehouse',
      'Galpon': 'Warehouse/Shed',
      'Casa': 'House',
      'Casa vacacional': 'Vacation House',
      'Apartamento': 'Apartment',
      'Apartamento vacacional': 'Vacation Apartment',
      'Terreno': 'Land',
      'Ático': 'Penthouse',
      'Dúplex': 'Duplex',
      'Loft': 'Loft',
      'Townhouse': 'Townhouse',
      'Estudio': 'Studio',
      'Inversión': 'Investment',
      'Tienda': 'Store',
      'Hotel': 'Hotel',
      'Restauración': 'Restaurant',
      'Patio Industrial': 'Patio Industrial',
      'Agricultura y bosques': 'Agriculture & Forests',
      'Centro Comercial': 'Shopping Center',
      'Otro': 'Other',
      'bedrooms_field': 'Bedrooms',
      'floors_field': 'Floors/Levels',
      'garden_field': 'Garden',
      'pool_field': 'Pool',
      'furnished_field': 'Furnished',
      'interior_location_field': 'Interior Location (Shop/Level)',
      'spaces_count': '{0} spaces',
      'question': 'Question',
      'answer': 'Answer',
      'any_value': 'Any',
      'min_label': 'Min',
      'max_label': 'Max',
      'minimum_suffix': '(minimum)',
      'security_availability': 'Security availability',
      'pool_availability': 'Pool availability',
      'additional_features': 'Features',
      'terrace_field': 'Terrace',
      'balcony_field': 'Balcony',
      'patio_field': 'Patio',
      'garage_field': 'Garage',
      'power_generator_field': 'Power Generator',
      'water_tank_field': 'Water Tank',
      'grill_field': 'Grill',
      'elevator_field': 'Elevator',
      'security_field': 'Security',
      'pets_allowed_field': 'Pets Allowed',
      'children_allowed_field': 'Children Allowed',
      'waterfront_field': 'Waterfront',
      'seaview_field': 'Sea View',
      'year_built_field': 'Year Built',
      'plot_area_field': 'Plot Area (m²)',
      'basement_field': 'Basement',
      'fitted_kitchen_field': 'Kitchen',
      'tennis_court_field': 'Tennis Court',
      'interior_location_hint': 'e.g. Shop 5, Level 1 / 2nd Floor, Apt 4B',
      'delivery_status_field': 'Delivery status',
      'has_electricity_field': 'Electricity',
      'has_water_connections_field': 'Water connections',
      'has_restroom_access_field': 'Restroom access',
      'has_ac_connection_field': 'A/C connection',
      'floor_level_field': 'Floor level',
      'has_storage_office_area_field': 'Internal Storage/Office area',
      'obra_gris': 'Shell & Core',
      'semi_acabado': 'Semi-finished',
      'listo_para_ocupar': 'Ready to occupy',
      'incluido_en_direccion': 'Specified in address',
      'planta_baja': 'Ground floor',
      'mezzanina': 'Mezzanine',
      'primer_piso': '1st floor',
      'segundo_piso': '2nd floor',
      'tercer_piso': '3rd floor',
      'cuarto_piso': '4th floor',
      'Piscina': 'Pool',
      'Terraza': 'Terrace',
      'Balcón': 'Balcony',
      'Patio': 'Patio',
      'Garaje': 'Garage',
      'Ascensor': 'Elevator',
      'Security': 'Security',
      'Pets Allowed': 'Pets Allowed',
      'Children Allowed': 'Children Allowed',
      'Waterfront': 'Waterfront',
      'Amoblado': 'Furnished',
      'Sótano': 'Basement',
      'Vista al mar': 'Sea View',
      'Cocina Empotrada': 'Fitted Kitchen',
      'Parrillera': 'Grill',
      // Geolocation
      'country_field': 'Country',
      'state_field': 'State/Province',
      'location_section': 'Geographic Location',
      'filter_country': 'Country',
      'filter_state': 'State/Province',
      'filter_city': 'City',
      'locations_manager': 'Locations Manager',
      'dist_by_city': 'City Distribution',
      'props': 'props',
      'locations_menu': 'Locations',
      'add_new_country': 'Add New Country',
      'select_country': 'Select a country',
      'tab_marketing': 'Marketing',
      'tab_requests': 'Requests',
      'active_strategy': 'Active Referral Strategy',
      'strategy_1_desc': 'Strategy 1: \$1 USD monthly discount per referral.',
      'strategy_2_desc': 'Strategy 2: Capacity bonus per referral + Salesperson commissions.',
      'strategy_3_desc': 'Strategy 3 (Mixed): \$1.00 USD discount + Capacity bonus.',
      'salespersons': 'Salespersons (Freelance)',
      'alias': 'Alias / Nickname',
      'commission_pct': '% Commission',
      'commissions': 'Commissions',
      'pending': 'Pending',
      'paid': 'Paid',
      'earning': 'Earning',
      'referred_companies': 'Referred Agencies',
      'successful_referrals': 'Successful Referrals',
      'select_state': 'Select a state',
      'confirm_delete': 'Confirm Deletion',
      'sure_delete_country': 'Are you sure you want to delete the country \$val and all its states and cities?',
      'sure_delete_state': 'Are you sure you want to delete the state \$val and all its cities?',
      'sure_delete_city': 'Delete the city \$val?',
      'add_state_to': 'Add State to',
      'add_city_to': 'Add City to',
      'delete': 'Delete',
      'add': 'Add',
      'name_hint': 'Name...',
      'geo_select_country': 'Select a country',
      'geo_select_state': 'Select a state',
      'geo_select_city': 'Select a city',
      'geo_distribution': 'Geographic Distribution',
      'top_cities': 'Properties by City',
      // Super Admin Panel
      'super_admin_panel': 'Super Admin Panel',
      'edit_company': 'Edit Agency',
      'new_company': 'New Agency',
      'company_name': 'Agency Name',
      'company_abbr': 'Abbreviation (3-5 letters)',
      'company_domain': 'Web Domain',
      'primary_color': 'Primary Color (Hex)',
      'secondary_color': 'Secondary Color (Hex)',
      'contact_email': 'Contact Email',
      'contact_phone': 'Contact Phone',
      'is_demo': 'Is Demo?',
      'is_active': 'Active',
      'no_companies': 'No agencies registered',
      'deactivate': 'Deactivate',
      'activate': 'Activate',
      'refresh': 'Refresh',
      // Global search
      'global_search_subtitle': 'Global Property Search',
      'global_search_hint': 'Search across all companies...',
      'all_companies': 'All',
      'results': 'results',
      'owners': 'Owners',
      'owners_count': 'Owners',
      'leads_count': 'Leads',
      'agents': 'Agents',
      'new_user': 'New Agent',
      'edit_user': 'Edit Agent',
      'role': 'Role',
      'role_super_admin': 'Super Admin',
      'role_admin': 'Administrator',
      'role_company_admin': 'Agency Admin',
      'role_agent': 'Agent',
      'role_client': 'Client',
      'photo_of': 'Photo {0} of {1}',
      'assign_company': 'Assign Agency',
      'no_company': '(No agency)',
      'no_users': 'No agents registered',
      'super_panel': 'Super Panel',
      'login_intro': 'Enter your credentials',
      // Demo
      'demo_banner': '🎭 Demo agency — changes may be periodically reset',
      'demo_budget_disabled': 'Feature disabled in demo mode',
      // Super Admin tabs
      'tab_companies': 'Agencies',
      'tab_users': 'Team',
      'company_logos': 'Agency Logos',
      'full_logo': 'Logo (Desktop)',
      'abbr_logo': 'Logo (Mobile)',
      'social_networks': 'Social Networks',
      // Billing Tab
      'tab_billing': 'Billing',
      'check_subs': 'Check Subscriptions (Cron)',
      'batch_reminder': 'Batch Reminder (5 days)',
      'register_payment': '✅ Register Payment',
      'reactivate_btn': '🔓 Reactivate',
      'suspend_btn': '🚫 Suspend',
      'payment_confirm_title': 'Confirm Payment',
      'amount_placeholder': 'Amount (USD)',
      'ref_placeholder': 'Reference / Bank',
      'notes_placeholder': 'Notes (Optional)',
      'confirm_activate': 'Confirm and Activate',
      'suspend_company_q': 'Suspend agency?',
      'suspend_company_warn': 'This will block access to {0} immediately.',
      // Agenda/Calendar
      'agenda': 'Agenda',
      'agenda_new_appointment': 'New Appointment',
      'agenda_edit_appointment': 'Edit Appointment',
      'agenda_client_name': 'Client Name',
      'agenda_phone': 'Phone',
      'agenda_date': 'Appointment Date',
      'agenda_time': 'Time',
      'agenda_property': 'Property to visit',
      'agenda_search_property': 'Search property...',
      'agenda_status': 'Appointment Status',
      'agenda_status_pending': 'Pending',
      'agenda_status_confirmed': 'Confirmed',
      'agenda_status_cancelled': 'Cancelled',
      'agenda_status_done': 'Done',
      'agenda_no_appointments': 'No appointments this day',
      'agenda_today_badge': 'appointments today',
      'agenda_delete_confirm': 'Delete this appointment?',
      'agenda_saved': 'Appointment saved',
      'agenda_deleted': 'Appointment deleted',
      'agenda_select_property': 'Select a property',
      'agenda_search_hint': 'Search by Ref.',
      'agenda_today': 'Today',
      'agenda_month_view': 'Month',
      'agenda_week_view': 'Week',
      'agenda_day_view': 'Day',
      'agenda_assigned_agent': 'Assigned Agent',
      'agenda_all_agents': 'All Agents',
      'agenda_select_agent': 'Select agent',
      'agenda_prop_ref': 'Prop. Ref. / Ref. Propiedad',
      'selected_label': 'Selected',
      'view_on_map': 'View on map',
      'my_location': 'My location',
      'assign_on_map': 'Locate on map',
      'geocode_address': 'Geocode address',
      'location_not_found': 'Could not find location: {0}',
      'geocoding': 'Searching coordinates...',
      'coordinates_field': 'Coordinates (Lat, Lng)',
      'loc_not_specified': 'Location not specified',
      'property_location': 'Property',
      'user_location': 'You',
      'weekly_visitors': '{0} visitors',
      'this_week': 'this week',
      // Map / Location
      'assign_location': 'Assign Location',
      'map_tap_hint': 'Tap on the map to mark the exact property location.',
      'confirm_location': 'Confirm Location',
      'geocoding_failed': 'Could not find the address on the map.',
      'no_location': 'Location not selected',
      'search_location': 'Search address...',
      'invite_re_agency': 'Invite Real Estate Agency',
      'invite_godmother_agency': 'Inviting Agency (Your Agency)',
      'invite_godmother_email': 'Your Contact Email',
      'invite_recipient_email': 'Recipient Agency Email',
      'invite_email_hint': 'Example: contact@friendlyagency.com',
      'invite_send_btn': 'SEND INVITATION',
      'invite_success_title': 'Invitation Sent!',
      'invite_success_msg': 'When the agency successfully registers, you will receive your rewards in the system.',
      'invite_send_another': 'Send another invitation',
      'invite_desc': 'Invite another real estate agency to join the platform and earn automatic bonuses every time an agency completes its registration thanks to you.',
      'invite_title_card': 'Grow with Alveo',
      'invite_reward_properties': '+2 Properties',
      'invite_reward_properties_desc': 'limit bonus',
      'invite_reward_photos': '+2 Photos',
      'invite_reward_photos_desc': 'per property',
      'invite_reward_discount': '-\$1 Month',
      'invite_reward_discount_desc': 'Monthly discount',
      'invite_disclaimer': '*Accumulated discount limit: 25% of your plan value. Space capacities have no limit.',
      'trial_info_with_price': '7-day free trial. Then {0}/mo.',
      // Register screen
      'register_title': 'Join Alveo',
      'register_hero': '🚀 Create your own real estate platform today.',
      'register_trial_info': '7-day free trial. Then \${0}/mo.',
      'register_trial_info_unknown': '7-day free trial.',
      'register_logo_pc': 'Logo for PC',
      'register_logo_mobile': 'Logo Mobile',
      'register_company_name': 'Agency Name',
      'register_domain_label': 'Your Alveo Address (Link)',
      'register_domain_helper': 'Choose a short name for your portal (e.g. myagency). Only lowercase letters and numbers. This will be your permanent link.',
      'register_subdomain_hint': 'e.g. myagency',
      'register_domain_unavailable': 'Domain not available',
      'register_domain_available': '✅ Domain available',
      'register_url_preview': 'Your URL will be',
      'register_your_name': 'Your Name',
      'register_email': 'Email Address',
      'register_email_hint': 'valid email address',
      'register_email_invalid': 'Invalid email',
      'register_password': 'Password (Admin)',
      'register_password_min': 'Minimum 6 characters',
      'register_phone': 'Phone',
      'register_social_networks': 'Social Networks',
      'register_whatsapp_required': 'WhatsApp required',
      'register_language': 'Platform Language',
      'register_plan': 'Plan',
      'register_plan_monthly': 'Monthly: \${0}',
      'register_plan_annual': 'Annual: \${0}',
      'register_trial_start': 'Trial Start (7 days)',
      'register_trial_end': 'Trial Expiration',
      'register_regional': 'Regional Settings',
      'register_detecting': 'Detecting your location...',
      'register_detected': 'Country detected by your IP: {0}',
      'register_ip_locked': 'Country was automatically detected by your IP and cannot be changed to ensure correct pricing.',
      'register_ip_lock_icon': 'Country locked by IP detection',
      'register_branding': 'Agency Colors',
      'register_primary_color': 'Primary Color',
      'register_secondary_color': 'Secondary Color',
      'register_hex_link': 'Get your hex codes here: htmlcolorcodes.com',
      'register_how': 'How did you hear about Alveo?',
      'register_channel_organic': 'Organic (own initiative)',
      'register_channel_salesperson': 'By executive (support)',
      'register_channel_broker': 'Another real estate agency',
      'register_alias_label': 'Salesperson alias',
      'register_alias_hint': 'e.g. mark123',
      'register_broker_email': 'Broker\'s email',
      'register_referred_by': 'Recommended by Broker:\n{0}',
      'register_recommended_by': 'Recommended by:\n{0}',
      'register_add_referral': 'Add referral',
      'register_change': 'Change',
      'register_broker_question': 'Were you recommended by a broker?',
      'register_submit': 'Register now',
      'register_domain_check_first': 'Please check subdomain availability before continuing.',
      'register_success_title': 'Congratulations! Your Alveo platform is ready',
      'register_success_access': 'You can now access your portal at:',
      'register_success_email': '📧 Check your email for your access credentials.',
      'register_go_portal': 'GO TO MY PORTAL NOW',
      'register_welcome_email_sent': 'We have also sent a welcome email to {0}.',
      'view_billing_history': 'VIEW PAYMENT HISTORY',
      'report_payment_title': 'Report Payment',
      'report_payment_desc': 'Enter your bank transfer details to renew your subscription.',
      'origin_bank_label': 'Origin Bank',
      'origin_bank_hint': 'Ex: Chase, Wells Fargo...',
      'reference_number_label': 'Reference Number',
      'reference_required': 'Reference required',
      'current_plan_label': 'Current plan: {0}',
      'payment_reported_success': 'Payment reported successfully. The admin will review it soon.',
      'trial_ending_soon': 'Your free trial ends in {0} {1}.',
      'subscription_expired_urgent': 'Subscription expired. Pay soon to avoid suspension!',
      'subscription_ending_soon': 'Your subscription expires in {0} {1}.',
      'confirm_rejection_title': 'Confirm Rejection',
      'confirm_rejection_msg': 'Are you sure you want to reject this request? This action cannot be undone.',
      'super_admin_billing_tab_title': 'Billing',
      'company_logos_title': 'AGENCY LOGOS',
      'general_summary_title': 'GENERAL SUMMARY',
      'contact_info_title': 'CONTACT INFORMATION',
      'regional_settings_title': 'REGIONAL SETTINGS',
      'plan_limits_title': 'PLAN & LIMITS',
      'mrr_real_label': 'MRR (Real 30d)',
      'mrr_potential_label': 'MRR (Potential)',
      'subscribers_label': 'Subscribers',
      'trial_users_label': 'On Trial',
      'suspended_users_label': 'Suspended',
      'pending_label': 'Pending',
      'pending_approvals_title': 'Payments Pending Approval',
      'no_pending_payments': 'No pending payments.',
      'receipt_label': 'Receipt:',
      'view_fullscreen': 'View Fullscreen',
      'reject_btn': 'Reject',
      'approve_activate_btn': 'Approve & Activate',
      'close_btn': 'Close',
      'billing_cycle_label': 'Billing Cycle / Plan',
      'base_price_label': 'Base Price \$ (Monthly)',
      'max_props_label': 'Base Properties Limit',
      'max_photos_label': 'Base Photos Limit',
      'show_referral_option': 'Show Referral Option',
      'show_organic_affiliate': 'Show Organic Affiliate Banner',
      'active': 'ACTIVE',
      'inactive': 'INACTIVE',
      'm2': 'Meters (m²)',
      'ft2': 'Feet (ft²)',
      'area_unit_label': 'Area Unit',
      'currency_label': 'Default Currency',
      'start_date_label': 'Start Date',
      'expiration_date_label': 'Expiration',
      'min_limit_label': 'Min Limit (-25%)',
      'full_logo_label': 'Full Logo',
      'abbr_logo_label': 'Abbreviated Logo',
      'approve_request_title': 'Approve Request',
      'approve_request_body': 'Do you want to create the agency "{0}" and activate it in Trial?',
      'approve_create_btn': 'Approve & Create',
      'company_created_activated': 'Agency created and activated',
      'no_pending_requests': 'No pending requests',
      'contact_label_field': 'Contact:',
      'domain_label_field': 'Domain:',
      'special_country_price': 'Special price by country',
      'standard_price': 'Standard price',
      'per_month': '/month',
      'per_year_annual': '/year (annual)',
      'approve_activate_trial_btn': 'APPROVE & ACTIVATE TRIAL',
      'strategy_updated': 'Strategy updated to: {0}',
      'alias_name_required': 'Alias and Name are required',
      'country_header': 'COUNTRY',
      'monthly_header': 'MONTHLY',
      'annual_header': 'ANNUAL',
      'floor_price_header': 'FLOOR REF.',
      'delete_country_price_title': 'Delete special price',
      'delete_country_price_body': 'Do you want to delete the price configured for {0} and return to the global base?',
      'monthly_price_label_field': 'Monthly price (USD, min. \$5)',
      'floor_price_label_field': 'Referral floor (min. \$5)',
      'floor_price_helper': 'Minimum price after referral discounts',
      'annual_calculated': 'Annual calculated: \$',
      'one_month_free': '(1 month free)',
      'min_5_error': 'Minimum \$5.00',
      'floor_min_5_error': 'Floor minimum \$5.00',
      'floor_greater_error': 'Floor cannot be higher than monthly price',
      'bank_account_info_field': 'Bank Account Info',
      'deactivate_salesperson_title': 'Deactivate Executive',
      'deactivate_salesperson_body': 'Are you sure you want to deactivate "{0}"? They will remain in the system but cannot be assigned to new operations.',
      'commissions_empty': 'No registered commissions',
      'mark_paid': 'Mark Paid',
      'active_btn': 'Active',
      'inactive_btn': 'Inactive',
      'date_header': 'Date',
      'company_header': 'Agency',
      'amount_header': 'Amount',
      'status_header': 'Status',
      'actions_header': 'Actions',
      'user_deleted_success': 'User deleted successfully',
      'no_name': 'No name',
      // Contract
      'contract_section_header': '📄 Review and accept the contract before continuing',
      'contract_accept': 'I have read and accept the Alveo Service Agreement',
      'contract_accept_date': 'Acceptance date',
      'contract_required': 'You must accept the contract to submit your request',
      // Social Networks
      'whatsapp_label': 'WhatsApp *',
      'instagram_label': 'Instagram',
      'facebook_label': 'Facebook',
      'telegram_label': 'Telegram',
      // Regional
      'state_label': 'State / Province',
      'city_field': 'City',
      'currency_label_field': 'Currency',
      'unit_label_field': 'Area Unit',
      'meters_label': 'Meters (m²)',
      'feet_label': 'Feet (ft²)',
      // Prices
      'special_price_for': 'Special price for {0}!',
      'standard_price_for': 'Standard price for {0}',
      'monthly_short': 'Monthly',
      'annual_short': 'Annual',
      // Months
      'month_1': 'January', 'month_2': 'February', 'month_3': 'March', 'month_4': 'April',
      'month_5': 'May', 'month_6': 'June', 'month_7': 'July', 'month_8': 'August',
      'month_9': 'September', 'month_10': 'October', 'month_11': 'November', 'month_12': 'December',
      'month_1_abbr': 'Jan', 'month_2_abbr': 'Feb', 'month_3_abbr': 'Mar', 'month_4_abbr': 'Apr',
      'month_5_abbr': 'May', 'month_6_abbr': 'Jun', 'month_7_abbr': 'Jul', 'month_8_abbr': 'Aug',
      'month_9_abbr': 'Sep', 'month_10_abbr': 'Oct', 'month_11_abbr': 'Nov', 'month_12_abbr': 'Dec',
      'clear_filter': 'Clear Filter',
      'filter_by_date': 'Filter by Date',
      'commissions_trend': 'Commissions Trend',
      'popular_likes': 'Popular (Likes)',
      'popular_views': 'Popular (Views)',
      'no_chart_data': 'Not enough data for the chart.',
      'total_collected': 'Total Collected',
      'agency_retention': 'Agency Retention',
      'pending_payouts': 'Pending Payout',
      'commission_detail': 'Detail',
      'operation_details': 'Operation Details',
      'location': 'Location',
      'operation': 'Operation',
      'close_date': 'Close Date',
      'total_commission': 'Total Commission',
      'agency_retention_pct': 'Agency Retention ({0}%)',
      'agent_pool': 'Agents Pool',
      'agent_distribution': 'Distribution to Agents',
      'agent_unknown': 'Unknown Agent',
      'commission_pct_of': '{0}% of commission',
      'company_must_collect_first': 'The agency must collect the commission first.',
      'confirm_payment': 'Confirm Payment',
      'confirm_payment_body': 'Confirm payment of {0} to {1}?',
      'confirm': 'Confirm',
      'current_status': 'Current Status:',
      'mark_collected': 'Mark Collected',
      'delete_commission': 'Delete Commission',
      'delete_commission_body': 'Are you sure you want to delete this commission? The property will be "Available" again.',
      'commission_deleted': 'Commission deleted successfully.',
      'delete_error': 'Error deleting: {0}',
      'pdf_error': 'Error generating PDF: {0}',
      'client_name_required': 'Enter the client name for Other Services.',
      'agent_split_error': 'The sum of percentages must be 100% (Current: {0}%)',
      'commission_registered': 'Commission registered successfully.',
      'client_name': 'Client Name',
      'op_rental_mgmt': 'Rental Management',
      'op_other_services': 'Other Services',
      'final_price': 'Final Price (\$)',
      'commission_collected': 'Commission Collected (\$)',
      'agency_amount': 'Agency Amount',
      'notes_optional': 'Notes (Optional)',
      'notes': 'Notes:',
      'concept_label': 'By concept of:',
      'agent_split': 'Agent Split',
      'add_agent': 'Add Agent',
      'total_must_be_100': 'Total must be 100%. Current: {0}%',
      'agent': 'Agent',
      'register_operation': 'Register Operation and Commission',
      'all': 'All',
      'owner': 'Owner',
      'person_type': 'Person Type',
      'default_commission_pct': 'Default Commission %',
      'tax_settings': 'Tax Settings',
      'tax_label': 'Tax Label',
      'tax_percentage': 'Tax Percentage',
      'confirm_save_commission': 'Confirm Commission',
      'confirm_save_commission_body': 'Do you want to save changes to this commission?',
      'pdf_internal': 'Operation',
      'pdf_invoice': 'Owner Invoice',
      'pdf_agent_receipts': 'Agent Receipts',
      'no_agents_to_pay': 'No agents assigned',
      'no_owner_found': 'Owner not found',
      'signature': 'Signature',
      'amount_received': 'Amount Received',
      'footer': 'This document is a digital receipt generated by Alveo Real Estate Platform.',
      'invoice_title': 'COMMISSION INVOICE',
      'tax_id': 'Tax ID',
      'received_from': 'Received from:',
      'agent_name': 'In favor of:',
      'agent_receipt': 'PAYMENT RECEIPT',
      'Persona Natural': 'Natural Person',
      'Persona Juridica': 'Legal Entity',
      'Ente Gubernamental': 'Government Entity',
      'total_filtered': 'Total Filtered',
      'all_f': 'All',
      'pending_plural': 'Pending',
      'collected_plural': 'Collected',
      'paid_plural': 'Paid',
      'no_commissions': 'No commissions registered.',
      'unknown_property': 'Unknown Property',
      'closed': 'Closed',
      'register_commission': 'Register Commission',
      'collected_f': 'Collected',
      'paid_f': 'Paid',
      'export_excel': 'Export to Excel',
      'excel_report_generated': 'Excel report generated successfully',
      'excel_generation_error': 'Error generating Excel: {0}',
      'limit_reached_msg': 'Property limit reached. Refer another broker to gain +2 slots!',
      'my_public_profile': 'My Public Profile',
      'username_slug': 'Personal Link (Alias)',
      'username_slug_help': 'This will be your unique web link to share your catalog with clients:',
      'username_hint': 'Only lowercase letters, numbers and hyphens',
      'contact_whatsapp': 'Contact WhatsApp',
      'bio_description': 'Bio / Description',
      'link_preview': 'Your link preview:',
      'link_copied': 'Link copied to clipboard',
      'save_success': 'Saved successfully',
      'my_commissions': 'My Commissions',
    }
  };

  String get(String key, [List<dynamic>? args]) {
    // Get value from current locale, fallback to Spanish, then to key name
    String? value = _localizedValues[locale.languageCode]?[key];
    
    if (value == null && locale.languageCode != 'es') {
      value = _localizedValues['es']?[key];
    }
    
    value ??= key;

    if (args != null) {
      for (int i = 0; i < args.length; i++) {
        value = value!.replaceAll('{$i}', args[i].toString());
      }
    }
    return value!;
  }

  static AppLocalizations of(BuildContext context) {
    // Fallback to Spanish if no provider found or locale missing
    return AppLocalizations(Localizations.localeOf(context));
  }
}
