import 'dart:typed_data';
import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import '../models/property_commission.dart';
import '../models/company.dart';
import '../models/owner.dart';

class CommissionPdfService {
  static const Map<String, Map<String, String>> _i18n = {
    'es': {
      'title': 'COMPROBANTE DE COMISIÓN',
      'ref': 'Referencia:',
      'date': 'Fecha de Cierre:',
      'property': 'Inmueble:',
      'operation': 'Operación:',
      'status': 'Estado:',
      'collected': 'Total Cobrado:',
      'agent_distribution': 'DISTRIBUCIÓN A AGENTES',
      'agent_name': 'Agente',
      'agent_pct': 'Porcentaje',
      'agent_amount': 'Monto',
      'agent_status': 'Estado Pago',
      'paid': 'PAGADO',
      'pending': 'PENDIENTE',
      'collected_f': 'COBRADA',
      'notes': 'Notas:',
      'footer': 'Documento generado por Alveo PMS',
      'company': 'Agencia:',
      'agency_retention': 'Retención Agencia:',
      'agent_pool': 'Pool Agentes:',
      'client': 'Cliente:',
      'rental_mgmt': 'Gestión de Alquileres',
      'other_services': 'Otros Servicios',
      'invoice': 'FACTURA',
      'tax': 'Impuesto',
      'subtotal': 'Subtotal',
      'total': 'Total',
      'agent_receipt': 'RECIBO DE PAGO DE COMISIÓN',
      'received_from': 'Recibido de:',
      'amount_received': 'Monto Recibido:',
      'signature': 'Firma',
      'issuer': 'EMISOR:',
      'client_owner': 'CLIENTE (PROPIETARIO):',
      'description': 'Descripción',
      'operation_details': 'DETALLES DE LA OPERACIÓN',
      'commission_for': 'Comisión por',
      'property_label': 'Inmueble',
      'sale': 'Venta',
      'rental': 'Alquiler',
      'concept_label': 'Por concepto de:',
    },
    'en': {
      'title': 'COMMISSION RECEIPT',
      'ref': 'Reference:',
      'date': 'Closing Date:',
      'property': 'Property:',
      'operation': 'Operation:',
      'status': 'Status:',
      'collected': 'Total Collected:',
      'agent_distribution': 'AGENT DISTRIBUTION',
      'agent_name': 'Agent',
      'agent_pct': 'Percentage',
      'agent_amount': 'Amount',
      'agent_status': 'Payment Status',
      'paid': 'PAID',
      'pending': 'PENDING',
      'collected_f': 'COLLECTED',
      'notes': 'Notes:',
      'footer': 'Document generated by Alveo PMS',
      'company': 'Agency:',
      'agency_retention': 'Agency Retention:',
      'agent_pool': 'Agent Pool:',
      'client': 'Client:',
      'rental_mgmt': 'Rental Management',
      'other_services': 'Other Services',
      'invoice': 'INVOICE',
      'tax': 'Tax',
      'subtotal': 'Subtotal',
      'total': 'Total',
      'agent_receipt': 'COMMISSION PAYMENT RECEIPT',
      'received_from': 'Received from:',
      'amount_received': 'Amount Received:',
      'signature': 'Signature',
      'issuer': 'ISSUER:',
      'client_owner': 'CLIENT (OWNER):',
      'description': 'Description',
      'operation_details': 'OPERATION DETAILS',
      'commission_for': 'Commission for',
      'property_label': 'Property',
      'sale': 'Sale',
      'rental': 'Rental',
      'concept_label': 'By concept of:',
    }
  };

  pw.MemoryImage? _logoImage;

  Future<void> _loadLogo() async {
    if (_logoImage != null) return;
    try {
      final logoBytes = await rootBundle.load('assets/images/logo_full.png');
      _logoImage = pw.MemoryImage(logoBytes.buffer.asUint8List());
    } catch (_) {}
  }

  Future<Uint8List> generateReceipt(PropertyCommission commission, Company company, {String languageCode = 'es'}) async {
    final pdf = pw.Document();
    final t = _i18n[languageCode] ?? _i18n['es']!;
    final currencyFormat = NumberFormat.currency(symbol: '\$', decimalDigits: 2);
    final dateFormat = DateFormat('dd/MM/yyyy');

    // Intentar cargar logo (puede que no exista en memoria local si es URL web, pero simulamos si hay asset local)
    pw.MemoryImage? logoImage;
    try {
      final logoBytes = await rootBundle.load('assets/images/logo_full.png');
      logoImage = pw.MemoryImage(logoBytes.buffer.asUint8List());
    } catch (_) {}

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  if (logoImage != null) pw.Image(logoImage, width: 150) else pw.Text(company.name, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text(t['title']!, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
                      pw.SizedBox(height: 4),
                      pw.Text("${t['ref']} ${commission.refNumber}", style: const pw.TextStyle(fontSize: 14)),
                      pw.Text("${t['date']} ${dateFormat.format(commission.closedDate)}", style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                    ],
                  ),
                ],
              ),
              pw.Divider(height: 32, thickness: 2, color: PdfColors.grey300),

              // Company Info
              pw.Text("${t['company']} ${company.name}", style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
              if (company.contactEmail != null) pw.Text(company.contactEmail!),
              if (company.contactPhone != null) pw.Text(company.contactPhone!),
              pw.SizedBox(height: 24),

              // Property & Operation Info
              pw.Container(
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(color: PdfColors.grey100, borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8))),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        if (commission.property != null) ...[
                          pw.Text("${t['property']} ${commission.property?.title}", style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                          pw.Text(commission.property?.address ?? ''),
                        ] else if (commission.clientName != null) ...[
                          pw.Text("${t['client']} ${commission.clientName}", style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                        ],
                        pw.SizedBox(height: 8),
                        pw.Text("${t['operation']} ${
                          commission.operationType == 'Venta' ? t['sale'] :
                          commission.operationType == 'Alquiler' ? t['rental'] :
                          commission.operationType == 'Gestión de Alquileres' ? t['rental_mgmt'] : 
                          commission.operationType == 'Otros Servicios' ? t['other_services'] : 
                          commission.operationType
                        }"),
                        pw.Text("${t['status']} ${
                          commission.status == 'paid' ? t['paid'] : 
                          commission.status == 'pending' ? t['pending'] : 
                          commission.status == 'collected' ? (t['collected_f'] ?? 'COBRADA') :
                          commission.status.toUpperCase()
                        }", style: pw.TextStyle(color: commission.status == 'paid' ? PdfColors.green : PdfColors.orange)),
                      ],
                    ),
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.end,
                      mainAxisAlignment: pw.MainAxisAlignment.center,
                      children: [
                        pw.Text(t['collected']!, style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
                        pw.Text(currencyFormat.format(commission.totalCollected), style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.green800)),
                      ],
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 12),
              
              // Agency Split info
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.end,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text("${t['agency_retention']} ${NumberFormat("#,###.##").format(commission.agencyRetentionPct)}% = ${currencyFormat.format(commission.agencyRetentionAmount)}", 
                              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
                      pw.Text("${t['agent_pool']} ${currencyFormat.format(commission.totalCollected - commission.agencyRetentionAmount)}", 
                              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 20),

              // Agents Table
              pw.Text(t['agent_distribution']!, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
              pw.SizedBox(height: 12),
              pw.TableHelper.fromTextArray(
                headers: [t['agent_name']!, t['agent_pct']!, t['agent_amount']!, t['agent_status']!],
                data: commission.agents.map((agent) => [
                  agent.agentName ?? 'Desconocido',
                  '${agent.percentage}%',
                  currencyFormat.format(agent.amount),
                  agent.isPaid ? t['paid']! : t['pending']!,
                ]).toList(),
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.blue800),
                rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300))),
                cellAlignments: {
                  0: pw.Alignment.centerLeft,
                  1: pw.Alignment.centerRight,
                  2: pw.Alignment.centerRight,
                  3: pw.Alignment.center,
                },
              ),

              pw.SizedBox(height: 24),
              if (commission.notes != null && commission.notes!.isNotEmpty) ...[
                pw.Text(commission.operationType == 'Otros Servicios' ? (t['concept_label'] ?? 'Por concepto de:') : (t['notes'] ?? 'Notas:'), style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.Text(commission.notes!),
              ],

              pw.Spacer(),
              pw.Divider(color: PdfColors.grey300),
              pw.Container(
                alignment: pw.Alignment.center,
                child: pw.Text(t['footer']!, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }

  Future<Uint8List> generateOwnerInvoicePdf(PropertyCommission commission, Company company, Owner owner, {String languageCode = 'es'}) async {
    await _loadLogo();
    final pdf = pw.Document();
    final t = _i18n[languageCode] ?? _i18n['es']!;
    final currencyFormat = NumberFormat.currency(symbol: company.currencySymbol, decimalDigits: 2);
    final dateFormat = DateFormat('dd/MM/yyyy');

    final String pType = owner.personType.toLowerCase();
    final bool hasTax = pType.contains('juridica') || 
                       pType.contains('jurídica') || 
                       pType.contains('ente');
    
    final double taxPct = hasTax ? company.taxPercentage : 0.0;
    final double taxAmount = commission.totalCollected * (taxPct / 100.0);
    final double totalWithTax = commission.totalCollected + taxAmount;

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  if (_logoImage != null) pw.Image(_logoImage!, width: 150) else pw.Text(company.name, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text(t['invoice'] ?? 'FACTURA', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
                      pw.SizedBox(height: 4),
                      pw.Text("${t['ref']} ${commission.refNumber}", style: const pw.TextStyle(fontSize: 14)),
                      pw.Text("${t['date']} ${dateFormat.format(commission.closedDate)}", style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                    ],
                  ),
                ],
              ),
              pw.Divider(height: 32, thickness: 2, color: PdfColors.grey300),

              // Billing Info
              pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Expanded(
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(t['issuer']!, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                        pw.Text(company.name, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                        if (company.contactEmail != null) pw.Text(company.contactEmail!),
                        if (company.contactPhone != null) pw.Text(company.contactPhone!),
                      ],
                    ),
                  ),
                  pw.Expanded(
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(t['client_owner']!, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                        pw.Text(owner.fullName, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                        pw.Text(t[owner.personType] ?? owner.personType),
                        if (owner.phone != null) pw.Text(owner.phone!),
                      ],
                    ),
                  ),
                ],
              ),
              pw.SizedBox(height: 32),

              // Details
              pw.TableHelper.fromTextArray(
                headers: [t['description']!, t['agent_amount']!],
                data: [
                  [
                    "${t['commission_for']} ${
                      commission.operationType == 'Venta' ? t['sale'] :
                      commission.operationType == 'Alquiler' ? t['rental'] :
                      commission.operationType == 'Gestión de Alquileres' ? t['rental_mgmt'] : 
                      commission.operationType == 'Otros Servicios' ? t['other_services'] : 
                      commission.operationType
                    }${commission.property != null ? " - ${commission.property!.title}" : ""}",
                    currencyFormat.format(commission.totalCollected)
                  ],
                ],
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.blue800),
                cellAlignments: {0: pw.Alignment.centerLeft, 1: pw.Alignment.centerRight},
              ),

              pw.SizedBox(height: 20),

              // Totals
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.end,
                children: [
                  pw.Container(
                    width: 200,
                    child: pw.Column(
                      children: [
                        if (hasTax) ...[
                          pw.Row(
                            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                            children: [
                              pw.Text(t['subtotal'] ?? 'Subtotal'),
                              pw.Text(currencyFormat.format(commission.totalCollected)),
                            ],
                          ),
                          pw.Row(
                            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                            children: [
                              pw.Text("${company.taxLabel} (${taxPct % 1 == 0 ? taxPct.toInt() : taxPct}%)"),
                              pw.Text(currencyFormat.format(taxAmount)),
                            ],
                          ),
                          pw.Divider(),
                        ],
                        pw.Row(
                          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                          children: [
                            pw.Text(t['total'] ?? 'Total', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                            pw.Text(currencyFormat.format(totalWithTax), style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
                          ],
                        ),
                      ],
                    ),
                  ),
                ],
              ),

              if (commission.notes != null && commission.notes!.isNotEmpty) ...[
                pw.SizedBox(height: 20),
                pw.Text(commission.operationType == 'Otros Servicios' ? (t['concept_label'] ?? 'Por concepto de:') : (t['notes'] ?? 'Notas:'), style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.Text(commission.notes!),
              ],

              pw.Spacer(),
              pw.Divider(color: PdfColors.grey300),
              pw.Container(
                alignment: pw.Alignment.center,
                child: pw.Text(t['footer']!, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }

  Future<Map<String, Uint8List>> generateAgentReceipts(PropertyCommission commission, Company company, {String languageCode = 'es'}) async {
    await _loadLogo();
    final Map<String, Uint8List> results = {};
    final t = _i18n[languageCode] ?? _i18n['es']!;
    final currencyFormat = NumberFormat.currency(symbol: company.currencySymbol, decimalDigits: 2);
    final dateFormat = DateFormat('dd/MM/yyyy');

    for (var agent in commission.agents) {
      final pdf = pw.Document();
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                 // Header
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    if (_logoImage != null) pw.Image(_logoImage!, width: 120) else pw.Text(company.name, style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.end,
                      children: [
                        pw.Text(t['agent_receipt'] ?? 'RECIBO DE PAGO', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
                        pw.Text("${t['ref']} ${commission.refNumber}-${agent.agentName?.substring(0,3).toUpperCase() ?? 'AGT'}", style: const pw.TextStyle(fontSize: 10)),
                        pw.Text("Fecha: ${dateFormat.format(DateTime.now())}", style: const pw.TextStyle(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                pw.Divider(height: 32),

                pw.SizedBox(height: 20),
                pw.Text("${t['received_from'] ?? 'Recibido de:'} ${company.name}", style: pw.TextStyle(fontSize: 12)),
                pw.SizedBox(height: 8),
                pw.Text("${t['agent_name'] ?? 'A favor de:'} ${agent.agentName}", style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 24),

                pw.Container(
                  padding: const pw.EdgeInsets.all(16),
                  decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey400), borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8))),
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text(t['amount_received'] ?? 'Monto Recibido:', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                      pw.Text(currencyFormat.format(agent.amount), style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.green800)),
                    ],
                  ),
                ),

                pw.SizedBox(height: 20),
                pw.Text("Concepto: Pago de comisión por ${commission.operationType} del inmueble ${commission.property?.title ?? 'N/A'} (Ref: ${commission.property?.refNumber ?? 'N/A'})"),
                pw.Text("Porcentaje asignado: ${agent.percentage}%"),

                pw.Spacer(),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                  children: [
                    pw.Column(
                      children: [
                        pw.Container(width: 150, decoration: const pw.BoxDecoration(border: pw.Border(top: pw.BorderSide(color: PdfColors.black)))),
                        pw.Text(company.name, style: const pw.TextStyle(fontSize: 10)),
                      ],
                    ),
                    pw.Column(
                      children: [
                        pw.Container(width: 150, decoration: const pw.BoxDecoration(border: pw.Border(top: pw.BorderSide(color: PdfColors.black)))),
                        pw.Text(agent.agentName ?? '', style: const pw.TextStyle(fontSize: 10)),
                        pw.Text(t['signature'] ?? 'Firma Recibido', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
                      ],
                    ),
                  ],
                ),
                pw.SizedBox(height: 40),
                pw.Divider(color: PdfColors.grey300),
                pw.Container(
                  alignment: pw.Alignment.center,
                  child: pw.Text(t['footer']!, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
                ),
              ],
            );
          }
        )
      );
      results[agent.agentName ?? 'Agent_${agent.agentId}'] = await pdf.save();
    }
    return results;
  }
}
